version: "3.8"

services:
  mediFlow-db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: medi_flow
      MYSQL_USER: 425428_julien
      MYSQL_PASSWORD: jUlien123*
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d

  mediflow-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - mediFlow-db
    environment:
      JWT_SECRET: 58795412
      SALT_ROUNDS: 5
      PORT: 3000
      DB_HOST: mediFlow-db
      DB_USER: 425428_julien
      DB_NAME: medi_flow
      DB_PASSWORD: jUlien123*
      MAILER_HOST: smtp.mailgun.org
      MAILER_PORT: 587
      MAILER_USER: soutadejulien@sandbox56816325903d4c668c58bd92a673c576.mailgun.org
      MAILER_PASSWORD: jUlien123
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app

volumes:
  mysql_data:
