version: "3.8"

services:
  mediFlow-db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: medi_flow
      MYSQL_USER: medi_flow
      MYSQL_PASSWORD: medi_flow123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d

  mediflow-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - mediFlow-db
    env_file:
      - .env
    environment:
      JWT_SECRET: 58795412
      SALT_ROUNDS: 5
      PORT: 3000
      DB_HOST: mediFlow-db
      DB_USER: medi_flow
      DB_NAME: medi_flow
      DB_PASSWORD: medi_flow123
    ports:
      - "3008:3000"
    volumes:
      - ./server:/app

volumes:
  mysql_data:
